### ISSUE TITLE
Single quotes in comments are converted to backticks when the following text contains a closing parenthesis

### ISSUE THREAD

**Issue by mythmon** [Mossop/vscode-backticks#16]
**STR**
1. Type the following
    ```
    /* ' */)
    ```
2. Place the cursor before the closing parenthesis.
3. Type `{`.

**Expected results**
A `{` is typed and no other changes are made.

**Actual results**
A `{` is typed and the `'` is changed to a backtick.

---

Single line and multiline comments are both affected. If there are two quotes in the comment, it works as expected. A `$` is not required before the bracket.

**Comment by Mossop** [comment]
So I've filed #17 for the `$` not being needed as that's probably a separate fix. Accidentally converting quotes in comments I can understand, I need to make the simple JS parser understand comments. Needing the closing parenthesis is just weird...
